POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbXNkYWwiLCJpZCI6IjZhOTFjY2I4MjMzMzU2NjI0ZTU2MTM5YyIsImlhdCI6MTc4Nzk1NDEzNX0.igSEsw--20DEldYs0iWz2jPA7f3H46jlm2fO3_Nxr4o

{
  "title": "The Example Blog",
  "author": "Johnny Boy",
  "url": "https://example.com"
}